apiVersion: batch/v1
kind: CronJob
metadata:
  name: morning-pod-restart
spec:
  schedule: 0 14 * * *
  concurrencyPolicy: Allow
  suspend: false
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            DataClass: Low
        spec:
          containers:
            - name: restart-pods
              image: 'bitnami/kubectl:latest'
              command:
                - /bin/sh
                - '-c'
                - >
                  kubectl get deployments -n a9cb09-dev -l app=airflow -o
                  custom-columns=:metadata.namespace,:metadata.name,:kind |
                  while read namespace name kind; do
                    if [ "$kind" = "Deployment" ]; then
                      kubectl rollout restart deployment $name -n $namespace;
                    fi
                  done
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: openmetadata-admin
          serviceAccount: openmetadata-admin
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1