apiVersion: batch/v1
kind: CronJob
metadata:
  name: nightly-pod-restart
spec:
  schedule: "0 0 * * *"  # Runs at midnight every day
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: restart-pods
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - >
              kubectl get deployments,statefulsets,daemonsets --all-namespaces -l airflow -o custom-columns=:metadata.namespace,:metadata.name,:kind | while read namespace name kind; do
                if [ "$kind" = "Deployment" ]; then
                  kubectl rollout restart deployment $name -n $namespace;
                elif [ "$kind" = "StatefulSet" ]; then
                  kubectl rollout restart statefulset $name -n $namespace;
                elif [ "$kind" = "DaemonSet" ]; then
                  kubectl rollout restart daemonset $name -n $namespace;
                fi
              done
          restartPolicy: OnFailure