apiVersion: v2
appVersion: 1.4.1
dependencies:
- condition: airflow.enabled
  name: airflow
  repository: https://airflow-helm.github.io/charts
  version: 8.8.0
- condition: opensearch.enabled
  name: opensearch
  repository: https://opensearch-project.github.io/helm-charts/
  version: 2.12.1
description: Helm Dependencies for OpenMetadata
home: https://open-metadata.org/
icon: https://open-metadata.org/assets/favicon.png
keywords:
- metadata
- data-science
- data
- machine-learning
- automation
- big-data
- bigdata
- artificial-intelligence
- datascience
- data-engineering
- data-catalog
- metadata-api
- governance
- data-profiling
- metadata-management
- dataengineering
- dataquality
- bigdataanalytics
- datadiscovery
maintainers:
- email: support@open-metadata.org
  name: OpenMetadata
name: openmetadata-dependencies
sources:
- https://github.com/open-metadata/OpenMetadata
- https://github.com/open-metadata/openmetadata-helm-charts
type: application
version: 1.4.1
