# Default values for OpenMetadata.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# Overrides the openmetadata config file with the help of Environment Variables
# Below are defaults as per openmetadata-dependencies Helm Chart Values
openmetadata:
  config:
    upgradeMigrationConfigs:
      debug: false
      # You can pass the additional argument flags to the openmetadata-ops.sh migrate command
      # Example if you want to force migration runs, use additionalArgs: "--force"
      additionalArgs: ""
    # Values can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL
    logLevel: INFO
    clusterName: openmetadata
    openmetadata:
      host: openmetadata
      # URI to use with OpenMetadata Alerts Integrations
      uri: "http://openmetadata:8585"
      port: 8585
      adminPort: 8586
    elasticsearch:
      enabled: true
      host: opensearch
      searchType: opensearch
      port: 9200
      scheme: http
      clusterAlias: ""
      # Value in Bytes
      payLoadSize: 10485760
      connectionTimeoutSecs: 5
      socketTimeoutSecs: 60
      batchSize: 100
      searchIndexMappingLanguage: "EN"
      keepAliveTimeoutSecs: 600
      trustStore:
        enabled: false
        path: ""
        password:
          secretRef: "elasticsearch-truststore-secrets"
          secretKey: "openmetadata-elasticsearch-truststore-password"
      auth:
        enabled: false
        username: "elasticsearch"
        password:
          secretRef: elasticsearch-secrets
          secretKey: openmetadata-elasticsearch-password
    database:
      enabled: true # DF-NOTE: previously true
      host: postgresql # DF-NOTE: previously 'mysql'
      port: 5432 # DF-NOTE: previously 3306
      driverClass: org.postgresql.Driver # DF-NOTE: values found at https://docs.open-metadata.org/v1.3.x/deployment/bare-metal#configure-postgres-connection
      dbScheme: postgresql # DF-NOTE: previously  mysql
      databaseName: openmetadata_db
      auth:
        username: openmetadata_user
        password:
          secretRef: db-secrets # DF-NOTE: previously 'mysql-secrets'
          secretKey: openmetadata-db-password # DF-NOTE: previously 'openmetadata-mysql-password'
      dbParams: "allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
      maxSize: 50
      minSize: 10
      initialSize: 10
      checkConnectionWhileIdle: true
      checkConnectionOnBorrow: true
      evictionInterval: 5 minutes
      minIdleTime: 1 minute
    pipelineServiceClientConfig:
      enabled: true
      className: "org.openmetadata.service.clients.pipeline.airflow.AirflowRESTClient"
      # endpoint url for airflow
      apiEndpoint: http://openmetadata-dependencies-web:8080
      # this will be the api endpoint url of OpenMetadata Server
      metadataApiEndpoint: http://openmetadata:8585/api
      # possible values are "no-ssl", "ignore", "validate"
      verifySsl: "no-ssl"
      hostIp: ""
      ingestionIpInfoEnabled: false
      # healthCheckInterval in seconds
      healthCheckInterval: 300
      # local path in Airflow Pod
      sslCertificatePath: "/no/path"
      auth:
        enabled: true
        username: admin
        password:
          secretRef: airflow-secrets
          secretKey: openmetadata-airflow-password
        trustStorePath: ""
        trustStorePassword:
          secretRef: ""
          secretKey: ""
    authorizer:
      enabled: true
      className: "org.openmetadata.service.security.DefaultAuthorizer"
      containerRequestFilter: "org.openmetadata.service.security.JwtFilter"
      initialAdmins: # DF-NOTE: Admins are named by beginning of bc gov email
      - "richard.pardo-figueroa"
      - "abigail.michel"
      - "krishna.rajendharan"
      allowedEmailRegistrationDomains:
      - "gov.bc.ca" # DF-NOTE: previously "all"
      principalDomain: "gov.bc.ca" # DF-NOTE: previously "open-metadata.org"
      enforcePrincipalDomain: false
      enableSecureSocketConnection: false
      useRolesFromProvider: false
    authentication: # DF-NOTE: Uses BCGov Common Hosted Single Sign-On, these values are environment-specific!!
      enabled: true
      clientType: confidential # DF-NOTE: previously public
      provider: "custom-oidc" # DF-NOTE: previously "basic"
      publicKeys: # DF-NOTE: previously "http://openmetadata:8585/api/v1/system/config/jwks"
      - "https://test.loginproxy.gov.bc.ca/auth"
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/auth" # authorization endpoint
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token"  # token endpoint
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/certs"
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/token/introspect"
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/userinfo"
      - "https://test.loginproxy.gov.bc.ca/auth/realms/standard/protocol/openid-connect/logout"
      authority: "https://test.loginproxy.gov.bc.ca/auth/realms/standard" # "http://localhost:8081/auth/realms/data-sec" # DF-NOTE: previously "https://accounts.google.com"
      clientId: "nrm-data-catalogue-5456"
      callbackUrl: "https://nr-data-catalogue-test.apps.emerald.devops.gov.bc.ca/callback" # previously "http://localhost:8585/callback" as per documentation
      responseType: code # DF-NOTE: previously id_token, not sure why 'code' works instead of others
      jwtPrincipalClaims:
      - "email"
      - "preferred_username"
      - "sub"
      jwtPrincipalClaimsMapping: []
      # jwtPrincipalClaimsMapping:
      # - username:sub
      # - email:email
      enableSelfSignup: false # DF-NOTE: disabled
      oidcConfiguration:
        enabled: true # DF-NOTE: previously false
        oidcType: ""
        clientId: # DF-NOTE: provided by CSS app
          secretRef: oidc-secrets
          secretKey: openmetadata-oidc-client-id
        clientSecret: # DF-NOTE: provided by CSS app
          secretRef: oidc-secrets
          secretKey: openmetadata-oidc-client-secret
        scope: "openid email profile offline_access" # DF-NOTE: These are all approved, see dev.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration
        discoveryUri: "https://test.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration"
        useNonce: true
        preferredJwsAlgorithm: RS256
        responseType: code
        disablePkce: true
        callbackUrl: "https://nr-data-catalogue-test.apps.emerald.devops.gov.bc.ca/callback"  # DF-NOTE: matches the redirect URI from CSS, previously http://openmetadata:8585/callback
        serverUrl:  "https://nr-data-catalogue-test.apps.emerald.devops.gov.bc.ca" # DF-NOTE: previously http://openmetadata:8585
        clientAuthenticationMethod: client_secret_post # DF-NOTE: This is approved, see test.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration
        tenant: ""
        maxClockSkew: ""
        tokenValidity: "3600"
        customParams: ""
      ldapConfiguration:
        host: localhost
        port: 10636
        dnAdminPrincipal: "cn=admin,dc=example,dc=com"
        dnAdminPassword:
          secretRef: ldap-admin-secret
          secretKey: openmetadata-ldap-secret
        userBaseDN: "ou=people,dc=example,dc=com"  # DF-NOTE: would be "dc=idir,dc=BCGOV"
        mailAttributeName: email
        maxPoolSize: 3
        sslEnabled: false
        groupBaseDN: ""
        roleAdminName: ""
        allAttributeName: ""
        usernameAttributeName: ""
        groupAttributeName: ""
        groupAttributeValue: ""
        groupMemberAttributeName: ""
        authRolesMapping: ""
        authReassignRoles: []
        # Possible values are CustomTrustStore, HostName, JVMDefault, TrustAll
        truststoreConfigType: TrustAll
        trustStoreConfig:
          customTrustManagerConfig:
            trustStoreFilePath: ""
            trustStoreFilePassword:
              secretRef: ""
              secretKey: ""
            trustStoreFileFormat: ""
            verifyHostname: true
            examineValidityDates: true
          hostNameConfig:
            allowWildCards: false
            acceptableHostNames: []
          jvmDefaultConfig:
            verifyHostname: true
          trustAllConfig:
            examineValidityDates: true
      saml:
        debugMode: false
        idp:
          entityId: ""
          ssoLoginUrl: ""
          idpX509Certificate:
            secretRef: ""
            secretKey: ""
          authorityUrl: "http://openmetadata:8585/api/v1/saml/login"
          nameId: "urn:oasis:names:tc:SAML:2.0:nameid-format:emailAddress"
        sp:
          entityId: "http://openmetadata:8585/api/v1/saml/metadata"
          acs: "http://openmetadata:8585/api/v1/saml/acs"
          spX509Certificate:
            secretRef: ""
            secretKey: ""
          spPrivateKey:
            secretRef: ""
            secretKey: ""
          callback: "http://openmetadata:8585/saml/callback"
        security:
          strictMode: false
          validateXml: false
          tokenValidity: 3600
          sendEncryptedNameId: false
          sendSignedAuthRequest: false
          signSpMetadata: false
          wantMessagesSigned: false
          wantAssertionsSigned: false
          wantAssertionEncrypted: false
          keyStoreFilePath: ""
          keyStoreAlias:
            secretRef: ""
            secretKey: ""
          keyStorePassword:
            secretRef: ""
            secretKey: ""

    jwtTokenConfiguration:
      enabled: true
      # File Path on Airflow Container
      rsapublicKeyFilePath: "./conf/public_key.der"
      # File Path on Airflow Container
      rsaprivateKeyFilePath: "./conf/private_key.der"
      jwtissuer: "open-metadata.org"
      keyId: "Gb389a-9f76-gdjs-a92j-0242bk94356"
    fernetkey:
      value: "jJ/9sz0g0OHxsfxOoSfdFdmk3ysNmPRnH3TUAbz3IHA="
      secretRef: ""
      secretKey: ""
    eventMonitor:
      enabled: true
      # Possible values are prometheus and cloudwatch
      type: prometheus
      batchSize: 10
      pathPattern:
      - "/api/v1/tables/*"
      - "/api/v1/health-check"
      # For value p99=0.99, p90=0.90, p50=0.50 etc.
      latency: []
      # - "p99=0.99"
      # - "p90=0.90"
      # - "p50=0.50"
    smtpConfig:
      enableSmtpServer: false
      emailingEntity: "OpenMetadata"
      supportUrl: "https://slack.open-metadata.org"
      transportationStrategy: "SMTP_TLS"
      openMetadataUrl: "http://openmetadata:8585"
      serverEndpoint: ""
      serverPort: ""
      senderMail: ""
      username: ""
      password:
        secretRef: ""
        secretKey: ""
    secretsManager:
      enabled: true
      # Possible values are db, aws, aws-ssm, managed-aws, managed-aws-ssm, in-memory, managed-azure-kv, azure-kv, gcp
      provider: db
      # Define the secret key ID as /<prefix>/<clusterName>/<key> for AWS
      # Define the secret key ID as <prefix>-<clusterName>-<key> for Azure
      prefix: ""
       # Add tags to the created resource, e.g., in AWS. Format is `[key1:value1,key2:value2,...]`
      tags: []
      additionalParameters:
        enabled: false
        region: ""
        # For AWS
        accessKeyId:
          secretRef: ""
          secretKey: ""
        secretAccessKey:
          secretRef: ""
          secretKey: ""
        # accessKeyId:
        #   secretRef: aws-access-key-secret
        #   secretKey: aws-key-secret
        # secretAccessKey:
        #   secretRef: aws-secret-access-key-secret
        #   secretKey: aws-key-secret
        # For Azure
        clientId:
          secretRef: ""
          secretKey: ""
        clientSecret:
          secretRef: ""
          secretKey: ""
        tenantId:
          secretRef: ""
          secretKey: ""
        vaultName:
          secretRef: ""
          secretKey: ""
        # clientId:
        #   secretRef: azure-client-id-secret
        #   secretKey: azure-key-secret
        # clientSecret:
        #   secretRef: azure-client-secret
        #   secretKey: azure-key-secret
        # tenantId:
        #   secretRef: azure-tenant-id-secret
        #   secretKey: azure-key-secret
        # vaultName:
        #   secretRef: azure-vault-name-secret
        #   secretKey: azure-key-secret
        # For GCP
        projectId:
          secretRef: ""
          secretKey: ""
        # projectId:
        #   secretRef: gcp-project-id-secret
        #   secretKey: gcp-key-secret
      # You can create Kubernetes secrets from AWS Credentials with the below command
      # kubectl create secret generic aws-key-secret \
      # --from-literal=aws-access-key-secret=<access_key_id_value> \
      # --from-literal=aws-secret-access-key-secret=<access_key_secret_value>
    web:
      enabled: true
      uriPath: "/api"
      hsts:
        enabled: false
        maxAge: "365 days"
        includeSubDomains: "true"
        preload: "true"
      frameOptions:
        enabled: false
        option: "SAMEORIGIN"
        origin: ""
      contentTypeOptions:
        enabled: false
      xssProtection:
        enabled: false
        onXss: true
        block: true
      csp:
        enabled: false
        policy: "default-src 'self'"
        reportOnlyPolicy: ""
      referrerPolicy:
        enabled: false
        option: "SAME_ORIGIN"
      permissionPolicy:
        enabled: false
        option: ""
      cacheControl: ""
      pragma: ""

networkPolicy:
  # If networkPolicy is true, following values can be set
  # for ingress on port 8585 and 8586
  enabled: false

  # Example Google SSO Auth Config
  # authorizer:
  #   className: "org.openmetadata.service.security.DefaultAuthorizer"
  #   containerRequestFilter: "org.openmetadata.service.security.JwtFilter"
  #   initialAdmins:
  #   - "suresh"
  #   principalDomain: "open-metadata.org"
  # authentication:
  #   provider: "google"
  #   publicKeys:
  #   - "https://www.googleapis.com/oauth2/v3/certs"
  #   authority: "https://accounts.google.com"
  #   clientId: "<client_id>"
  #   callbackUrl: "<callback_url>"

image:
  repository: artifacts.developer.gov.bc.ca/docker-remote/openmetadata/server # DF-NOTE: using Artifactory instead of docker.getcollate.io
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
  pullPolicy: "Always"

sidecars: []
# - name: "busybox"
#   image: "busybox:1.34.1"
#   imagePullPolicy: "Always"
#   command: ["ls"]
#   args: ["-latr", "/usr/share"]
#   env:
#   - name: DEMO
#     value: "DEMO"
#   volumeMounts:
#   - name: extras
#     mountPath: /usr/share/extras
#     readOnly: true

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "openmetadata"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: openmetadata-admin # DF-NOTE: manual because of limitations put in place by OCIO
automountServiceAccountToken: true
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 100

service:
  type: ClusterIP
  port: 8585
  adminPort: 8586
  annotations: {}

# Service monitor for Prometheus metrics
serviceMonitor:
  enabled: false
  interval: 30s
  annotations: {}
  labels: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: open-metadata.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: tls-open-metadata.local
    #   hosts:
    #     - open-metadata.local

extraEnvs:
# DF-NOTE: Important note about PBI ingestions, you need to also add the proxies below to the openmetadata-dependencies-config-envs secret
  - name: http_proxy
    value: 'http://swpxkam.gov.bc.ca:8080'
  - name:  https_proxy
    value: 'http://swpxkam.gov.bc.ca:8080'
  - name: no_proxy
    value: 'NO_PROXY=.cluster.local,.svc,10.91.0.0/16,172.30.0.0/16,127.0.0.1,localhost,.gov.bc.ca,openmetadata,openmetadata-dependencies'

envFrom: []
# - secretRef:
#     name: secret_containing_config

extraVolumes: []
# - name: extras
#   emptyDir: {}

extraVolumeMounts: []
# - name: extras
#   mountPath: /usr/share/extras
#   readOnly: true

# Provision for InitContainers to be running after the `run-db-migration` InitContainer
extraInitContainers: []

# Provision for InitContainers to be running before the `run-db-migration` InitContainer
preMigrateInitContainers: []

resources: # DF-NOTE: previously not enabled - but needs to be otherwise it will default to incorrect values
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 10m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
  httpGet:
    path: /healthcheck
    port: http-admin
readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 5
  httpGet:
    path: /
    port: http
startupProbe:
  timeoutSeconds: 10 # DF-NOTE: Added this value, as it was timing out after 1 second
  periodSeconds: 60
  failureThreshold: 5
  successThreshold: 1
  httpGet:
    path: /healthcheck
    port: http-admin

podDisruptionBudget:
  enabled: false
  config:
    maxUnavailable: "1"
    minAvailable: "1"

commonLabels: {}
podAnnotations: {}
